function plotdFbyF(dataset, Data, trialDetails, xtitle, ytitle, figureDetails, normalizeCell2Max)

if normalizeCell2Max
    for cell = 1:size(Data,1)
        Data(cell,:) = Data(cell,:)/max(Data(cell,:));
    end
end

imagesc(Data*100);
colorbar
colormap('jet')
z = colorbar;
if normalizeCell2Max == 1
    ylabel(z,'Normalized dF/F (%)', ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
else
    ylabel(z,'dF/F (%)', ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
end
%if sessionType == 9
if dataset.sessionType == 1
    title(['All Trials - Calcium Responses | ' ...
        dataset.mouse_name ' 250ms TEC S' num2str(dataset.session) ' | '...
        num2str(trialDetails.frameRate) ' Hz | '...
        num2str(dataset.nFrames) ' frames/trial'] , ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
elseif dataset.sessionType == 2
    title(['All Trials - Calcium Responses | ' ...
        dataset.mouse_name ' 350ms TEC S' num2str(dataset.session) ' | '...
        num2str(trialDetails.frameRate) ' Hz | '...
        num2str(dataset.nFrames) ' frames/trial'] , ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
elseif dataset.sessionType == 3
    title(['All Trials - Calcium Responses | ' ...
        dataset.mouse_name ' 500ms TEC S' num2str(dataset.session) ' | '...
        num2str(trialDetails.frameRate) ' Hz | '...
        num2str(dataset.nFrames) ' frames/trial'] , ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
elseif dataset.sessionType == 4
    title(['All Trials - Calcium Responses | ' ...
        dataset.mouse_name ' CS-only S' num2str(dataset.session) ' | '...
        num2str(trialDetails.frameRate) ' Hz | '...
        num2str(dataset.nFrames) ' frames/trial'] , ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
elseif dataset.sessionType == 5
    title(['All Trials - Calcium Responses | ' ...
        dataset.mouse_name ' Spontaneous S' num2str(dataset.session) ' | '...
        num2str(trialDetails.frameRate) ' Hz | '...
        num2str(dataset.nFrames) ' frames/trial'] , ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
else
    title(['All Trials - Calcium Responses | ' ...
        dataset.mouse_name ' ? S' num2str(dataset.session) ' | '...
        num2str(trialDetails.frameRate) ' Hz | '...
        num2str(dataset.nFrames) ' frames/trial'] , ...
        'FontSize', figureDetails.fontSize, ...
        'FontWeight', 'bold')
end
%set(gca,'XTick', frameRate*(1:2:17)) %NOTE: Starting 5 frames are skipped
%set(gca,'XTickLabel', ({1; 3; 5; 7; 9; 11; 13; 15; 17})) %NOTE: At 14.5 fps
%set(gca,'XTickLabel', ({1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; 17})) %NOTE: At 14.5 fps
xlabel(xtitle, ...
    'FontSize', figureDetails.fontSize,...
    'FontWeight', 'bold')
%set(gca,'YTick',[10, 20, 30, 40, 50, 60])
%set(gca,'YTickLabel',({10; 20; 30; 40; 50; 60}))
ylabel(ytitle, ...
    'FontSize', figureDetails.fontSize,...
    'FontWeight', 'bold')
set(gca,'FontSize', figureDetails.fontSize-2)